stack_id = "DendroBatchStack"

batch_service_role_id = f"{stack_id}-BatchServiceRole"
ecs_instance_role_id = f"{stack_id}-EcsInstanceRole"
batch_jobs_access_role_id = f"{stack_id}-BatchJobsAccessRole"
security_group_id = f"{stack_id}-security-group"
vpc_id = f"{stack_id}-vpc"
efs_file_system_id = f"{stack_id}-EfsFileSystem"
compute_env_gpu_id = f"{stack_id}-compute-env-gpu-1"
compute_env_cpu_id = f"{stack_id}-compute-env-cpu-1"
job_queue_gpu_id = f"{stack_id}-job-queue-gpu"
job_queue_cpu_id = f"{stack_id}-job-queue-cpu"
